# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
cassandra_host: "L-_52bbNpJOS3CwsZlveF4XgvNCWHBZExi7q7pKksxjfxT1Ywko7ol88H-dXZg=="
cassandra_username: "sT6xRTEePdj42G-t3rzeMe2-x-WYYA=="
cassandra_password: "maNgv4j-wTB59RU6Z35qoPSo4sZPyrY9oT-vSoleMu8="
cassandra_keyspace: "u_3N5wCqYWdlHRJQ3AFJm86TEA=="
